site_name: Ecliptic Seasons
site_url: https://example.com
site_description: A documentation for Ecliptic Seasons project
site_author: jianzoushihu
repo_url: https://github.com/joe-vettek/Ecliptic-Seasons
repo_name: Ecliptic Seasons

theme:
  name: 'material'
  language: 'en'


nav:
  - Home:
      - English:
          - Index: 'en/index.md'
          - Climate: 'zh/climate.md'
          - Crop: 'en/crop.md'
          - Compatibility: 'en/compat.md'
          - Datapack Base: 'zh/datapack.md'
          - Custom:
              - Model Definitions: 'zh/custom/model_definitions.md'
              - Snowy Block Models: 'zh/custom/snow_definitions.md'
              - Seasonal Block Models: 'zh/custom/season_definitions.md'
      - 中文:
          - 首页: 'zh/index.md'
          - 气候: 'zh/climate.md'
          - 作物: 'zh/crop.md'
          - 兼容性: 'zh/compat.md'
          - 数据包基本: 'zh/datapack.md'
          - 自定义:
            - 模型映射: 'zh/custom/model_definitions.md'
            - 覆雪方块定义与模型: 'zh/custom/snow_definitions.md'
            - 四季模型: 'zh/custom/season_definitions.md'


markdown_extensions:
  - toc:
      permalink: true
  - admonition

extra_css:
  - _static/css/custom.css
extra_javascript:
  - _static/js/custom.js

docs_dir: 'source'

extra:
  static_path: [ '[_static]' ]
  alternate:
    - name: English
      link: /en/latest/en/
      lang: en
    - name: 中文
      link: /en/latest/zh/
      lang: zh
plugins:
  - search


